package Registration;

import java.sql.*;
import Connexion.Connexion;
import javax.swing.JOptionPane;
import Login.LoginForm;
import javax.swing.*;
/**
 *
 * @author dell5
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Pre = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        CIN = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mdp = new javax.swing.JPasswordField();
        adr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMinimumSize(new java.awt.Dimension(800, 600));
        Background.setPreferredSize(new java.awt.Dimension(800, 600));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registration/automotive.png"))); // NOI18N
        Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 430, -1));

        Nom.setPreferredSize(new java.awt.Dimension(300, 30));
        Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomActionPerformed(evt);
            }
        });
        Background.add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 91, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setLabelFor(Nom);
        jLabel9.setText("Nom");
        jLabel9.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 90, 181, -1));

        Pre.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(Pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 132, -1, -1));

        username.setPreferredSize(new java.awt.Dimension(300, 30));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        Background.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 180, -1, -1));

        CIN.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(CIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 228, -1, -1));

        tel.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 276, -1, -1));

        email.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 324, -1, -1));

        mdp.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 372, -1, -1));

        adr.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(adr, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Prenom");
        jLabel8.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 132, 181, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nom d'utilisateur");
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 180, 181, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("CIN");
        jLabel6.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 228, 181, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("TÈlÈphone");
        jLabel4.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 276, 181, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Email");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 324, 181, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Mot de passe");
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 372, 181, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Adresse");
        jLabel7.setPreferredSize(new java.awt.Dimension(300, 30));
        Background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 420, 181, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("S'inscrire");
        Background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 11, -1, -1));

        jLabel11.setText("C'est rapide et facile .");
        Background.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("S'inscrire");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 120, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Vous avez dÈja un compte? cliquez ici pour se connecter.");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            int cin = Integer.parseInt(CIN.getText());
            String prenom = Pre.getText();
            String nom = Nom.getText();
            String user = username.getText();
            String password = mdp.getText();
            int numtel = Integer.parseInt(tel.getText());
            String mail = email.getText();
            String adresse = adr.getText();
        
            Connexion con = new Connexion();
            Statement st = con.connect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM fonctionnaire WHERE Username='"+user+"'");
            
           if(rs.next()){
               JOptionPane.showMessageDialog(null,"Compte d√©ja existant! veuillez utiliser un autre nom d'utilisateur","Inscription",JOptionPane.ERROR_MESSAGE);
               username.setText("");
           }
           else{
            
            st.executeUpdate("INSERT INTO fonctionnaire VALUES('"+user+"','"+password+"','"+cin+"','"+nom+"','"+prenom+"','"+numtel+"','"+mail+"','"+adresse+"');");
            JOptionPane.showMessageDialog(null,"Inscription effecut√© avec succ√©es","Inscription",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            LoginForm login = new LoginForm();
            login.setVisible(true);
            
           }
            
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed

    }//GEN-LAST:event_NomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
       LoginForm log = new LoginForm();
       log.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public boolean alpha(String x){
        for (int i=0; i<x.length(); i++){
            if (!(Character.isLetter(x.charAt(i)))){
                return false;
            }
        }
        return true;
    }
    
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JTextField CIN;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Pre;
    private javax.swing.JTextField adr;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField mdp;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
