/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GererDemandes;
import java.sql.*;
import GererVoitures.GererVoitures;
import GererClients.GererClients;
import javax.swing.table.DefaultTableModel;
import Connexion.Connexion;
import javax.swing.JOptionPane;
import java.util.Date;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;
import java.text.SimpleDateFormat;
import Login.LoginForm;
/**
 *
 * @author dell5
 */
public class GereDemandes extends javax.swing.JFrame {
    
    /**
     * Creates new form GereDemandes
     */
    public GereDemandes() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editer = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        cin1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        datedebut = new javax.swing.JTextField();
        dateretour = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        enregister2 = new javax.swing.JButton();
        refresh1 = new javax.swing.JButton();
        refresh2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Date de retour (AAAA-MM-JJ)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 227, 244, 16));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("CIN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, 90, 16));

        editer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        editer.setForeground(new java.awt.Color(255, 51, 51));
        editer.setText("Modifier les dates");
        editer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editerActionPerformed(evt);
            }
        });
        getContentPane().add(editer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        supprimer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        supprimer.setForeground(new java.awt.Color(255, 51, 51));
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 110, -1));

        cin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cin1ActionPerformed(evt);
            }
        });
        getContentPane().add(cin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 145, 150, -1));

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Gerer Les Voitures");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 416, 250, 40));

        jButton5.setBackground(new java.awt.Color(255, 51, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Gerer les demandes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 467, 250, 40));

        jButton6.setBackground(new java.awt.Color(255, 51, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Gerer les Clients");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 365, 250, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Numéro du Matricule");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 16));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Date de reservation (AAAA-MM-JJ)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 178, 322, 16));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Réservations");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 362, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom du Client", "CIN Client", "Voiture", "Date de Réservation", "Date de Retour", "Prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setMinimumSize(new java.awt.Dimension(60, 30));
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 656, 541));

        datedebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datedebutActionPerformed(evt);
            }
        });
        getContentPane().add(datedebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 201, 150, -1));

        dateretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateretourActionPerformed(evt);
            }
        });
        getContentPane().add(dateretour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 254, 150, -1));

        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        getContentPane().add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 97, 150, -1));

        enregister2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enregister2.setForeground(new java.awt.Color(255, 51, 51));
        enregister2.setText("Enregistrer");
        enregister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregister2ActionPerformed(evt);
            }
        });
        getContentPane().add(enregister2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, -1));

        refresh1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        refresh1.setText("Se déconnecter");
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1ActionPerformed(evt);
            }
        });
        getContentPane().add(refresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 518, 158, -1));

        refresh2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        refresh2.setForeground(new java.awt.Color(255, 51, 51));
        refresh2.setText("Charger");
        refresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2ActionPerformed(evt);
            }
        });
        getContentPane().add(refresh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 110, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Liste de réservations");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 25, 196, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editerActionPerformed
        try{
            String deb = JOptionPane.showInputDialog("Donnez la nouvelle date de debut (AAAA-MM-JJ)");
            String fin = JOptionPane.showInputDialog("Donnez la nouvelle date de retour (AAAA-MM-JJ)");
            Connexion con = new Connexion();
            Statement st = con.connect().createStatement();
            int id = Integer.parseInt(JOptionPane.showInputDialog("Donnez le numero de la réservation dont vous voulez modifier"));
            ResultSet rs = st.executeQuery("SELECT * FROM reservation where num_res='"+id+"'");
            if(rs.next()){
                st.executeUpdate("UPDATE reservation SET Date_Debut='"+deb+"', Date_Retour='"+fin+"' WHERE num_res='"+id+"'");
                JOptionPane.showMessageDialog(null,"Réservation modifiée!","Modification",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,"La réservation n'existe pas!","Erreur",JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_editerActionPerformed

    private void cin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cin1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        GererVoitures v = new GererVoitures();
        v.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        GererClients c = new GererClients();
        c.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void datedebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datedebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datedebutActionPerformed

    private void dateretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateretourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateretourActionPerformed

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed
    
    private void enregister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregister2ActionPerformed
        
        try{
            Connexion con = new Connexion();
            Statement st = con.connect().createStatement();
            if (num.getText().equals("") || cin1.getText().equals("") || datedebut.getText().equals("") || dateretour.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Le remplissage de tout les champs est obligatoire!","Erreur",JOptionPane.ERROR_MESSAGE);
            }
            else{
                int mat = Integer.parseInt(num.getText());
                int cin = Integer.parseInt(cin1.getText());
                String Dated = datedebut.getText();
                String Dater = dateretour.getText();
                
                ResultSet rs = st.executeQuery("SELECT etat FROM vehicule WHERE NumMatricule='"+mat+"'");
                if (!rs.next()){
                    JOptionPane.showMessageDialog(null,"Le véhicule n'existe pas!","Erreur",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(rs.getString(1).equals("Réservé")){
                        JOptionPane.showMessageDialog(null,"Le vehicule est déja réservé");
                    }
                    else{
                        rs = st.executeQuery("SELECT * FROM client WHERE CIN='"+cin+"'");
                        if (rs.next()==false){
                            JOptionPane.showMessageDialog(null,"Le client n'existe pas","Erreur",JOptionPane.ERROR_MESSAGE);
                        }
                        else{                           
                            rs = st.executeQuery("SELECT CIN_Client FROM reservation WHERE CIN_Client='"+cin+"'");
                            if (rs.next()){
                                JOptionPane.showMessageDialog(null,"Le client a déja une réservation courante","Erreur",JOptionPane.ERROR_MESSAGE);
                            }
                            else{
                                st.executeUpdate("INSERT INTO reservation VALUES(Num_res,'"+cin+"','"+mat+"',DATE '"+Dated+"',DATE '"+Dater+"');");
                                JOptionPane.showMessageDialog(null,"Réservation ajouté!","Ajout",JOptionPane.INFORMATION_MESSAGE);
                                st.executeUpdate("UPDATE vehicule SET etat='Réservé' WHERE NumMatricule='"+mat+"'");
                            }
                        }
                    }
                }
            }
                
   
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_enregister2ActionPerformed
    public long daysbetween(Date one, Date two){
        long diff = (one.getTime()-two.getTime())/86400000;
        return Math.abs(diff);
    }
    public Date formatDate(String date){
        String y = date.substring(0,date.indexOf("-"));
        String m = date.substring(date.indexOf("-")+1,date.lastIndexOf("-")-1);
        String d = date.substring(date.lastIndexOf("-")+1,date.length()-1);
        int year = Integer.parseInt(y);
        int month = Integer.parseInt(m);
        int day = Integer.parseInt(d);
        Date out = new Date(year,month,day);
        return out;
    }
    
    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        try{
            int id = Integer.parseInt(JOptionPane.showInputDialog("Donnez le numéro de la réservation à supprimer"));
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            Connexion con = new Connexion();
            Statement st = con.connect().createStatement();
            ResultSet rs = st.executeQuery("SELECT Date_Retour, NumMatricule FROM reservation WHERE Num_res='"+id+"'");
            if (rs.next()){
                int mat = rs.getInt(2);
                Date retour = formatDate(rs.getDate(1).toString());
                LocalDateTime now = LocalDateTime.now();
                Date current = formatDate(dtf.format(now));
                if (retour.compareTo(current) > 0){
                    String options[] = {"Oui","Non"};
                    int choix = JOptionPane.showOptionDialog(null, "La date de retour de cette réservation n'a pas encore arrivé! Vous etes sur de votre décision?","Avertissement",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[0]);
                    if (choix == 0){
                        st.executeUpdate("DELETE FROM reservation WHERE Num_res='"+id+"'");
                        st.executeUpdate("UPDATE vehicule SET etat='Disponible' WHERE NumMatricule='"+mat+"'");
                        JOptionPane.showMessageDialog(null,"Réservation supprimée!","Suppression",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else{
                    st.executeUpdate("DELETE FROM reservation WHERE Num_res='"+id+"'");
                    st.executeUpdate("UPDATE vehicule SET etat='Disponible' WHERE NumMatricule='"+mat+"'");
                    JOptionPane.showMessageDialog(null,"Réservation supprimée!","Suppression",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1ActionPerformed
        this.dispose();
        LoginForm log = new LoginForm();
        log.setVisible(true);
    }//GEN-LAST:event_refresh1ActionPerformed

    private void refresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2ActionPerformed
        try{
            DefaultTableModel tbmodel = (DefaultTableModel)table.getModel();
            tbmodel.setRowCount(0);
            Connexion con = new Connexion();
            Statement st = con.connect().createStatement();
            Statement st1 = con.connect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM reservation");
            Statement st2 = con.connect().createStatement();
            while(rs.next() != false){
                String cin = Integer.toString(rs.getInt(2));
                String mat = Integer.toString(rs.getInt(3));
                Date d1 = rs.getDate(4);
                Date d2 = rs.getDate(5);
                ResultSet rs1 = st1.executeQuery("SELECT Nom, Prenom from client where CIN='"+rs.getInt(2)+"'");
                rs1.next();
                String nomc = rs1.getString(2) + " " + rs1.getString(1);
                ResultSet rs2 = st2.executeQuery("SELECT m.PrixParJour from modele m, reservation r, vehicule v WHERE r.NumMatricule=v.NumMatricule AND v.Marque=m.Marque AND r.NumMatricule='"+rs.getInt(3)+"'");
                rs2.next();
                long numberOfDays = daysbetween(d1,d2);
                Float prix = numberOfDays * rs2.getFloat(1);
                SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
                String Date1 = sdf.format(d1);
                String Date2 = sdf.format(d2);
                String row[] = {Integer.toString(rs.getInt(1)),nomc,cin,mat,Date1,Date2,Float.toString(prix)};
                tbmodel.addRow(row);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_refresh2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GereDemandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GereDemandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GereDemandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GereDemandes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GereDemandes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cin1;
    private javax.swing.JTextField datedebut;
    private javax.swing.JTextField dateretour;
    private javax.swing.JButton editer;
    private javax.swing.JButton enregister2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField num;
    private javax.swing.JButton refresh1;
    private javax.swing.JButton refresh2;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
